### ISSUE TITLE
Unable to run ntLink on real Hifi and assembly data

### ISSUE THREAD

**Issue by Oieswarya** [bcgsc/ntLink#101]
Hello I am trying to run ntLink on an assembly of Caddisfly and I am getting this error:

indexlr 1.6.2: Using more than 5 threads does not scale, reverting to 5.
indexlr 1.6.2: Using more than 5 threads does not scale, reverting to 5.
make: *** [/home/.conda/envs/ntlink_env/bin/share/ntlink-1.3.10-0/ntLink:218: /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.z1000.n1.scaffold.dot] Error 120

I have used ntLink on many data but all of them were on simulated data. Is it something to do with the data?

This is the .o file log:
command time -v -o /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.tsv.time indexlr --long --pos --strand -k 32 -w 250 -t 32 /home/NCBIContigs/CaddisflyAssemblyRename.fa > /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.tsv
command time -v -o /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.z1000.n1.scaffold.dot.time  sh -c 'pigz -p32 -f -cd /home/SRAFiles/SRR15840267_withFasta/SRR15840267.fasta | \
indexlr --long --pos --strand --len -k 32 -w 250 -t 32 - | \
/home/.conda/envs/ntlink_env/bin/share/ntlink-1.3.10-0/bin/ntlink_pair.py -p /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.z1000 -n 1 -m /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.tsv -s 
/home/NCBIContigs/CaddisflyAssemblyRename.fa  \
-k 32 -a 1 -z 1000 -f 10 -x 0 --verbose -'
Running pairing stage of ntLink ...

Parameters:
	Read minimizer files:  ['-']
	-s  /home/NCBIContigs/CaddisflyAssemblyRename.fa
	-m  /home/NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.tsv
	-p  /home//NCBIContigs/CaddisflyAssemblyRename.fa.k32.w250.z1000
	-n  1
	-k  32
	-a  1
	-z  1000
	-f  10
	-x  0.0
2024-05-15 20:12:22.568305 : Reading minimizers /home/NCBIContigs/CaddisflyAssemblyRename.fa
2024-05-15 20:12:58.735838 : Reading fasta file /home/NCBIContigs/CaddisflyAssemblyRename.fa
2024-05-15 20:14:05.277788 : Finding pairs
Memory Usage of ntLink:
       JobID     MaxRSS  MaxVMSize               Start                 End CPUTimeRAW        NodeList 
------------ ---------- ---------- ------------------- ------------------- ---------- --------------- 
57258609                           2024-05-15T00:22:22 2024-05-15T00:22:23          1           cn116 
57258609.ba+      1044K    144396K 2024-05-15T00:22:22 2024-05-15T00:22:23          1           cn116 
57258609.ex+       980K    144300K 2024-05-15T00:22:22 2024-05-15T00:22:23          1           cn116 
57258621                           2024-05-15T00:23:05 2024-05-15T00:23:05          0           cn116 
57258621.ba+      1036K    144396K 2024-05-15T00:23:05 2024-05-15T00:23:05          0           cn116 
57258621.ex+       976K    144300K 2024-05-15T00:23:05 2024-05-15T00:23:05          0           cn116 
57258642                           2024-05-15T00:24:58 2024-05-15T00:24:59          1           cn116 
57258642.ba+      1044K    144396K 2024-05-15T00:24:58 2024-05-15T00:24:59          1           cn116 
57258642.ex+       980K    144300K 2024-05-15T00:24:58 2024-05-15T00:24:59          1           cn116 
57258661                           2024-05-15T00:26:19 2024-05-15T00:49:17       1378           cn116 
57258661.ba+      2204K    144396K 2024-05-15T00:26:19 2024-05-15T00:49:17       1378           cn116 
57258661.ex+       976K    144300K 2024-05-15T00:26:19 2024-05-15T00:49:17       1378           cn116 
57263187                           2024-05-15T07:54:18 2024-05-15T08:19:23       1505           cn123 
57263187.ba+      6376K    159076K 2024-05-15T07:54:18 2024-05-15T08:19:23       1505           cn123 
57263187.ex+       976K    144300K 2024-05-15T07:54:18 2024-05-15T08:19:23       1505           cn123 
57263221                           2024-05-15T08:19:49 2024-05-15T10:01:30       6101           cn123 
57263221.ba+    165176K    358804K 2024-05-15T08:19:49 2024-05-15T10:01:30       6101           cn123 
57263221.ex+       984K    144300K 2024-05-15T08:19:49 2024-05-15T10:01:30       6101           cn123 
57263390                           2024-05-15T09:26:52 2024-05-15T09:26:53          1           cn116 
57263390.ba+      1048K    144396K 2024-05-15T09:26:52 2024-05-15T09:26:53          1           cn116 
57263390.ex+       976K    144300K 2024-05-15T09:26:52 2024-05-15T09:26:53          1           cn116 
57263402                           2024-05-15T09:33:01 2024-05-15T09:33:02          1           cn116 
57263402.ba+      1052K    144396K 2024-05-15T09:33:01 2024-05-15T09:33:02          1           cn116 
57263402.ex+       980K    144300K 2024-05-15T09:33:01 2024-05-15T09:33:02          1           cn116 
57271525                           2024-05-15T15:54:26 2024-05-15T15:54:39         13           cn137 
57271525.ba+      1180K    144528K 2024-05-15T15:54:26 2024-05-15T15:54:40         14           cn137 
57271525.ex+      1016K    144264K 2024-05-15T15:54:26 2024-05-15T15:54:39         13           cn137 
57271529                           2024-05-15T15:54:49 2024-05-15T15:54:54          5           cn137 
57271529.ba+      1184K    144528K 2024-05-15T15:54:49 2024-05-15T15:54:55          6           cn137 
57271529.ex+         1M    144264K 2024-05-15T15:54:49 2024-05-15T15:54:54          5           cn137 
57271536                           2024-05-15T15:55:49 2024-05-15T16:26:16       1827           cn137 
57271536.ba+      7492K    243000K 2024-05-15T15:55:49 2024-05-15T16:26:16       1827           cn137 
57271536.ex+      1020K    144264K 2024-05-15T15:55:49 2024-05-15T16:26:16       1827           cn137 
57271588                           2024-05-15T16:03:30 2024-05-15T16:03:32          2           cn130 
57271588.ba+      1256K    144528K 2024-05-15T16:03:30 2024-05-15T16:03:32          2           cn130 
57271588.ex+      1200K    144484K 2024-05-15T16:03:30 2024-05-15T16:03:32          2           cn130 
57272243                           2024-05-15T16:42:27 2024-05-15T16:43:02         35           cn133 
57272243.ba+      2.50M    234356K 2024-05-15T16:42:27 2024-05-15T16:43:02         35           cn133 
57272243.ex+      1192K    144484K 2024-05-15T16:42:27 2024-05-15T16:43:02         35           cn133 
57272296                           2024-05-15T16:45:29 2024-05-15T16:50:05        276           cn133 
57272296.ba+      7484K    243000K 2024-05-15T16:45:29 2024-05-15T16:50:05        276           cn133 
57272296.ex+      1196K    144484K 2024-05-15T16:45:29 2024-05-15T16:50:05        276           cn133 
57273078                           2024-05-15T17:21:51 2024-05-15T17:21:53          2           cn104 
57273078.ba+      1052K    144404K 2024-05-15T17:21:51 2024-05-15T17:21:53          2           cn104 
57273078.ex+       908K    144168K 2024-05-15T17:21:51 2024-05-15T17:21:53          2           cn104 
57273096                           2024-05-15T18:17:51 2024-05-15T19:41:27       5016           cn101 
57273096.ba+  14428836K  16250324K 2024-05-15T18:17:51 2024-05-15T19:41:29       5018           cn101 
57273096.ex+       904K    144168K 2024-05-15T18:17:51 2024-05-15T19:41:29       5018           cn101 
57273305                           2024-05-15T17:30:57 2024-05-15T17:30:58          1           cn135 
57273305.ba+      1188K    144528K 2024-05-15T17:30:57 2024-05-15T17:30:58          1           cn135 
57273305.ex+      1020K    144264K 2024-05-15T17:30:57 2024-05-15T17:30:58          1           cn135 
57273320                           2024-05-15T17:32:28 2024-05-15T18:01:17       1729           cn135 
57273320.ba+  18761764K  19116036K 2024-05-15T17:32:28 2024-05-15T18:01:17       1729           cn135 
57273320.ex+      1020K    144264K 2024-05-15T17:32:28 2024-05-15T18:01:17       1729           cn135 
57274386                           2024-05-15T18:57:51 2024-05-15T19:25:19       1648           cn104 
57274386.ba+  30221992K  30574744K 2024-05-15T18:57:51 2024-05-15T19:25:19       1648           cn104 
57274386.ex+       908K    144168K 2024-05-15T18:57:51 2024-05-15T19:25:19       1648           cn104 
57274815                           2024-05-15T19:41:55 2024-05-15T19:41:57          2           cn101 
57274815.ba+      1040K    144404K 2024-05-15T19:41:55 2024-05-15T19:41:57          2           cn101 
57274815.ex+       904K    144168K 2024-05-15T19:41:55 2024-05-15T19:41:57          2           cn101 
57274837                           2024-05-15T19:46:08 2024-05-15T19:46:10          2           cn101 
57274837.ba+      1048K    144404K 2024-05-15T19:46:08 2024-05-15T19:46:10          2           cn101 
57274837.ex+       908K    144168K 2024-05-15T19:46:08 2024-05-15T19:46:10          2           cn101 
57274845                           2024-05-15T19:48:36 2024-05-15T19:48:38          2           cn101 
57274845.ba+      1048K    144404K 2024-05-15T19:48:36 2024-05-15T19:48:38          2           cn101 
57274845.ex+       904K    144168K 2024-05-15T19:48:36 2024-05-15T19:48:38          2           cn101 
57274857                           2024-05-15T19:51:03 2024-05-15T20:23:52       1969           cn101 
57274857.ba+      7484K    243000K 2024-05-15T19:51:03 2024-05-15T20:23:52       1969           cn101 
57274857.ex+       908K    144168K 2024-05-15T19:51:03 2024-05-15T20:23:52       1969           cn101 
57274899                           2024-05-15T20:11:54             Unknown      23200             sn4 
57274899.ex+                       2024-05-15T20:11:54             Unknown      23200             sn4 

This is the command I am using:
ntLink scaffold target=/home/NCBIContigs/CaddisflyAssemblyRename.fa reads=/home/SRAFiles/SRR15840267_withFasta/SRR15840267.fasta k=32 w=250 t=32 v=1

**Comment by Oieswarya** [comment]
I was not using soft links for my target and reads file and that was the issue. Now it is working.

**Comment by lcoombe** [comment]
Great, glad you found the solution, @Oieswarya!
Yes, you are right - the input files need to be in the current working directory, and making soft-links is a great way to achieve that.
