### ISSUE TITLE
make: Nothing to be done for 'pair'.

### ISSUE THREAD

**Issue by ply2022** [bcgsc/ntLink#88]
Hi, 

I am following the [Alternate Protocol 1: GENERATING LONG-READ TO CONTIG MAPPINGS WITH ntLink](https://currentprotocols.onlinelibrary.wiley.com/doi/10.1002/cpz1.733), but I received the following error message: 

**make: Nothing to be done for 'pair'.**

My script is:

**ntLink pair target=shasta_assembly.fa reads=all_pine_chopper_porechop_abi.fa t=5 sensitive=True paf=True**

I installed the protocol-specific dependency, miller, with conda. My target assembly (shasta_assembly.fa) and my long read file (all_pine_chopper_porechop_abi.fa) are in my current working directory.

Would you please help me resolve this issue? Thank you.

**Comment by lcoombe** [comment]
Hello @ply2022,

Have you run any other `ntLink` command with those input files in that directory? That message means that the file has found that the target output files are already in the current directory, so no new commands need to be run.

If you do have other ntLink files in the same directory, but want to run this command fresh, you could change into a fresh directory, make soft-links to the input files there, and launch the command. 
Alternatively, specifying the option `-B` to your `ntLink` command will force all commands to be run, whether or not some output files are already found in the directory.

I hope that helps - thank you for your interest in ntLink!
Lauren

**Comment by ply2022** [comment]
Hi Laurence, 

Thank you for the prompt reply! 

Yes, I ran the **ntLink scaffold** under the same working directory. **ntLink pair** works smoothly now after I ran it in the empty directory. 

Best,
Pei-Ling

**Comment by lcoombe** [comment]
Great, I'm glad to hear!
